//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anteproyecto
    {
        public Anteproyecto()
        {
            this.InformeTecnico = new HashSet<InformeTecnico>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int ID { get; set; }
        public string NombreProyecto { get; set; }
        public string Objetivo { get; set; }
        public string Justificacion { get; set; }
        public string Cronograma { get; set; }
        public string DescActividades { get; set; }
        public string Direccion { get; set; }
        public string NombreEmp { get; set; }
        public string GiroEmp { get; set; }
        public string DireccionEmp { get; set; }
        public string CargoEmp { get; set; }
        public string TelefonoEmp { get; set; }
        public string CorreoElecEmp { get; set; }
        public string estatus { get; set; }
    
        public virtual ICollection<InformeTecnico> InformeTecnico { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
