//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeTecnico
    {
        public InformeTecnico()
        {
            this.Usuario1 = new HashSet<Usuario>();
        }
    
        public int ID { get; set; }
        public int ProyectoID { get; set; }
        public int AlumnoID { get; set; }
        public string NombreProyecto { get; set; }
        public string NomEmp { get; set; }
        public string NomAlumno { get; set; }
        public string Carrera { get; set; }
        public string AsesorInterno { get; set; }
        public string AsesorExterno { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Agradecimientos { get; set; }
        public string Resumen { get; set; }
        public string Indice { get; set; }
        public string estatus { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual ICollection<Usuario> Usuario1 { get; set; }
    }
}
