//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoISEntities : DbContext
    {
        public ProyectoISEntities()
            : base("name=ProyectoISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anteproyecto> Anteproyecto { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Examen> Examen { get; set; }
        public virtual DbSet<InformeTecnico> InformeTecnico { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Residencia> Residencia { get; set; }
        public virtual DbSet<Tipousuario> Tipousuario { get; set; }
        public virtual DbSet<Titulacion> Titulacion { get; set; }
        public virtual DbSet<TitulacionProyecto> TitulacionProyecto { get; set; }
        public virtual DbSet<TitulacionTesis> TitulacionTesis { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<BancoProyecto> BancoProyecto { get; set; }
    }
}
