//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipousuario
    {
        public Tipousuario()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
