//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Titulacion
    {
        public int ID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string Estatus { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual TitulacionProyecto TitulacionProyecto { get; set; }
        public virtual TitulacionTesis TitulacionTesis { get; set; }
        public virtual Examen Examen { get; set; }
    }
}
