//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.InformeTecnico = new HashSet<InformeTecnico>();
            this.Residencia = new HashSet<Residencia>();
            this.Titulacion = new HashSet<Titulacion>();
            this.Anteproyecto = new HashSet<Anteproyecto>();
            this.InformeTecnico1 = new HashSet<InformeTecnico>();
        }
    
        public int NumeroDeControl { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public int CarreraID { get; set; }
        public int TipoUsuarioID { get; set; }
        public string Contraseña { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual ICollection<InformeTecnico> InformeTecnico { get; set; }
        public virtual ICollection<Residencia> Residencia { get; set; }
        public virtual Tipousuario Tipousuario { get; set; }
        public virtual ICollection<Titulacion> Titulacion { get; set; }
        public virtual ICollection<Anteproyecto> Anteproyecto { get; set; }
        public virtual ICollection<InformeTecnico> InformeTecnico1 { get; set; }
    }
}
